export const GET_ERRORS = 'GET_ERRORS'
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const LOAD_APPLICATIONS = 'LOAD_APPLICATIONS'
export const LOAD_APPLICATIONS_SUCCESS = 'LOAD_APPLICATIONS_SUCCESS'
export const LOAD_APPLICATIONS_FAILURE = 'LOAD_APPLICATIONS_FAILURE'

export const CHANGE_APPLICATION = 'CHANGE_APPLICATION'
export const CHANGE_APPLICATION_SUCCESS = 'CHANGE_APPLICATION_SUCCESS'
export const CHANGE_APPLICATION_FAILURE = 'CHANGE_APPLICATION_FAILURE'
